Repository kubeflow/kfctl, pull requests merged in 2019-11, with the labels that each got.

#75 fix endpoint test json field name
  testing/e2e/endpoint_ready_test.py
Labels: approved, lgtm, size/XS

#80 Add missing files
  config/zz_generated.deepcopy.go
  go.mod
  go.sum
  pkg/kfupgrade/kfupgrade.go.back
Labels: approved, lgtm, size/XL

#76 update coordinator/converters/gcp API for kfctlserver
  go.mod
  go.sum
  pkg/apis/apps/configconverters/v1alpha1.go
  pkg/apis/apps/configconverters/v1beta1.go
  pkg/apis/apps/kfconfig/types.go
  pkg/apis/apps/kfdef/v1beta1/application_types.go
  pkg/apis/apps/kfdef/v1beta1/application_types_test.go
  pkg/apis/apps/kfdef/v1beta1/testdata/kfctl_plugin_test.yaml
  pkg/kfapp/coordinator/coordinator.go
  pkg/kfapp/coordinator/coordinator_test.go
  pkg/kfapp/gcp/gcp.go
Labels: approved, lgtm, size/XL

#83 add presubmit tests
  prow_config.yaml
Labels: approved, lgtm, size/M

#78 Fix deps in kfapp and kfdef
  go.mod
  go.sum
  pkg/kfapp/aws/aws.go
  pkg/kfapp/aws/aws_plugin.go
  pkg/kfapp/gcp/gcp.go
  pkg/kfapp/gcp/gcp_plugin.go
  pkg/kfapp/gcp/gcp_plugin_test.go
  pkg/kfapp/gcp/gcp_test.go
Labels: approved, lgtm, size/L

#87 Enable Unittest
  prow_config.yaml
  testing/workflows/components/params.libsonnet
  testing/workflows/components/unit_tests.jsonnet
Labels: approved, lgtm, size/L

#90 Make KFCTL E2E tests self contained in repo
  prow_config.yaml
  py/kubeflow/__init__.py
  py/kubeflow/kfctl/__init__.py
  py/kubeflow/kfctl/testing/__init__.py
  py/kubeflow/kfctl/testing/ci/__init__.py
  py/kubeflow/kfctl/testing/ci/kfctl_e2e_workflow.py
  py/kubeflow/kfctl/testing/ci/kfctl_go_build_test.py
  py/kubeflow/kfctl/testing/ci/kfctl_go_deploy_test.py
  py/kubeflow/kfctl/testing/ci/update_jupyter_web_app.py
  py/kubeflow/kfctl/testing/pytests/conftest.py
  py/kubeflow/kfctl/testing/pytests/endpoint_ready_test.py
  py/kubeflow/kfctl/testing/pytests/kf_is_ready_test.py
  py/kubeflow/kfctl/testing/pytests/kfctl_delete_test.py
  py/kubeflow/kfctl/testing/pytests/kfctl_go_test.py
  py/kubeflow/kfctl/testing/pytests/kfctl_second_apply.py
  py/kubeflow/kfctl/testing/test_deploy.py
  py/kubeflow/kfctl/testing/test_deploy_test.py
  py/kubeflow/kfctl/testing/util/__init__.py
  py/kubeflow/kfctl/testing/util/application_util.py
  py/kubeflow/kfctl/testing/util/application_util_test.py
  py/kubeflow/kfctl/testing/util/deploy_utils.py
  py/kubeflow/kfctl/testing/util/gcp_util.py
  py/kubeflow/kfctl/testing/util/kfctl_go_test_utils.py
  py/kubeflow/kfctl/testing/util/run_with_retry.py
  py/kubeflow/kfctl/testing/util/vm_util.py
Labels: approved, lgtm, size/XXL

#92 update coordinator API
  go.mod
  pkg/kfapp/coordinator/coordinator.go
Labels: approved, lgtm, size/XS

#95 Disable failed tests due to ksonnet
  py/kubeflow/kfctl/testing/ci/kfctl_e2e_workflow.py
Labels: approved, lgtm, size/S

#88 Upgrade to kubernetes 1.15.0
  go.mod
  go.sum
  pkg/apis/apps/kfdef/v1beta1/zz_generated.deepcopy.go
  pkg/kfapp/gcp/gcp.go
  pkg/utils/k8utils.go
Labels: approved, lgtm, size/L

#98 keep literal secret when convert kfdef v1beta1 to kfconfig
  pkg/apis/apps/configconverters/v1beta1.go
Labels: approved, lgtm, size/S

#85 Copy KfConfig to /pkg
  Makefile
  pkg/kfconfig/doc.go
  pkg/kfconfig/gcp_plugin.go
  pkg/kfconfig/gcp_plugin_test.go
  pkg/kfconfig/register.go
  pkg/kfconfig/types.go
  pkg/kfconfig/zz_generated.deepcopy.go
Labels: approved, lgtm, size/XXL

#84 Copy plugins from kfapp to apis/apps as external API
  Makefile
  pkg/apis/apps/plugins/aws/aws.go
  pkg/apis/apps/plugins/aws/v1alpha1/doc.go
  pkg/apis/apps/plugins/aws/v1alpha1/register.go
  pkg/apis/apps/plugins/aws/v1alpha1/types.go
  pkg/apis/apps/plugins/aws/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/apps/plugins/gcp/gcp.go
  pkg/apis/apps/plugins/gcp/v1alpha1/doc.go
  pkg/apis/apps/plugins/gcp/v1alpha1/register.go
  pkg/apis/apps/plugins/gcp/v1alpha1/types.go
  pkg/apis/apps/plugins/gcp/v1alpha1/types_test.go
  pkg/apis/apps/plugins/gcp/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/apps/plugins/plugins.go
Labels: approved, lgtm, size/XL

#100 directly use plugin types in v1beta1.go
  pkg/kfconfig/loaders/v1beta1.go
Labels: approved, lgtm, size/M

#101 Fix kfctl_path in second_apply
  prow_config.yaml
  py/kubeflow/kfctl/testing/ci/kfctl_e2e_workflow.py
  py/kubeflow/kfctl/testing/ci/kfctl_go_deploy_test.py
  py/kubeflow/kfctl/testing/pytests/kfctl_second_apply.py
Labels: approved, lgtm, size/S

#109 Create README.md for KfDef v1beta1
  pkg/apis/apps/kfdef/v1beta1/README.md
Labels: approved, lgtm, size/M

#96 Update prow config to kfctl_istio_dex config
  prow_config.yaml
Labels: approved, lgtm, size/XS
