Repository kubeflow/kfctl, pull requests merged in 2019-12, with the labels that each got.

#107 Add tests to KfConfig v1beta1
  pkg/apis/apps/kfconfig/types_test.go
Labels: approved, lgtm, needs-ok-to-test, size/XL

#112 Set depth=all when checking out a specific branch
  py/kubeflow/kfctl/testing/ci/kfctl_e2e_workflow.py
Labels: approved, lgtm, size/S

#111 Add a GitHub action to auto-add/remove issues to needs triage project board
  .github/workflows/triage_issues.yaml
Labels: approved, lgtm, size/S

#123 Patch kubeflow control plane label
  pkg/utils/k8utils.go
Labels: approved, lgtm, size/S

#106 kfctl binary push to GCS
  py/kubeflow/kfctl/testing/util/kfctl_go_test_utils.py
Labels: approved, lgtm, size/S

#114 Add test data to KfConfig tests
  pkg/kfconfig/testdata/doc.go
  pkg/kfconfig/testdata/kfctl_plugin_test.yaml
  pkg/kfconfig/types_test.go
Labels: approved, lgtm, ok-to-test, size/S

#120 remove delete_storage flag
  cmd/kfctl/cmd/delete.go
  pkg/kfconfig/loaders/v1.go
  pkg/kfconfig/loaders/v1beta1.go
  py/kubeflow/kfctl/testing/pytests/kfctl_delete_test.py
Labels: approved, lgtm, size/M

#118 Support Kubeflow upgrades in kfctl (pt 2)
  go.mod
  go.sum
  pkg/kfapp/gcp/gcp.go
  pkg/kfupgrade/kfupgrade.go
Labels: approved, lgtm, size/L

#126 Fix unittest result propagation
  Makefile
Labels: approved, lgtm, size/XS

#110 Check host before actually delete kf
  cmd/kfctl/cmd/delete.go
  go.mod
  pkg/apis/apps/group.go
  pkg/apis/apps/kfdef/v1alpha1/zz_generated.deepcopy.go
  pkg/kfapp/coordinator/coordinator.go
  pkg/kfapp/kustomize/kustomize.go
  pkg/kfconfig/loaders/v1.go
  pkg/kfconfig/loaders/v1alpha1.go
  pkg/kfconfig/loaders/v1beta1.go
  pkg/utils/k8utils.go
  py/kubeflow/kfctl/testing/ci/kfctl_e2e_workflow.py
  py/kubeflow/kfctl/testing/pytests/kfctl_delete_wrong_cluster.py
Labels: approved, lgtm, size/L

#132 self signed cert for testing
  py/kubeflow/kfctl/testing/ci/kfctl_e2e_workflow.py
  py/kubeflow/kfctl/testing/pytests/conftest.py
  py/kubeflow/kfctl/testing/pytests/kfctl_go_test.py
Labels: approved, lgtm, size/M

#133 Add kubeflow/kfctl to list of the default repos.
  py/kubeflow/kfctl/testing/ci/kfctl_e2e_workflow.py
Labels: approved, lgtm, size/XS

#134 Allow the src root directory to be substituted into the config_path.
  py/kubeflow/kfctl/testing/ci/kfctl_e2e_workflow.py
  py/kubeflow/kfctl/testing/pytests/conftest.py
  py/kubeflow/kfctl/testing/pytests/kfctl_go_test.py
Labels: approved, lgtm, size/M

#136 disable dex test
  prow_config.yaml
Labels: approved, lgtm, size/M

#137 Pytorch pytest
  py/kubeflow/kfctl/testing/ci/kfctl_e2e_workflow.py
  py/kubeflow/kfctl/testing/pytests/pytorch_job_deploy.py
  py/kubeflow/kfctl/testing/pytests/testdata/pytorch_job.yaml
Labels: approved, lgtm, size/L

#144 fix the bug that only recognize iam service account
  pkg/kfapp/gcp/gcp.go
Labels: approved, lgtm, size/S

#142 jupyter pytest
  py/kubeflow/kfctl/testing/ci/kfctl_e2e_workflow.py
  py/kubeflow/kfctl/testing/pytests/jupyter_test.py
  py/kubeflow/kfctl/testing/pytests/testdata/jupyter_test.yaml
Labels: approved, lgtm, size/M

#147 add v1 support to E2E test
  py/kubeflow/kfctl/testing/pytests/kf_is_ready_test.py
  py/kubeflow/kfctl/testing/util/kfctl_go_test_utils.py
Labels: approved, lgtm, size/XS

#150 Automated cherry pick of #90: Make KFCTL E2E tests self contained in repo
  prow_config.yaml
  py/kubeflow/__init__.py
  py/kubeflow/kfctl/__init__.py
  py/kubeflow/kfctl/testing/__init__.py
  py/kubeflow/kfctl/testing/ci/__init__.py
  py/kubeflow/kfctl/testing/ci/kfctl_e2e_workflow.py
  py/kubeflow/kfctl/testing/ci/kfctl_go_build_test.py
  py/kubeflow/kfctl/testing/ci/kfctl_go_deploy_test.py
  py/kubeflow/kfctl/testing/ci/update_jupyter_web_app.py
  py/kubeflow/kfctl/testing/pytests/conftest.py
  py/kubeflow/kfctl/testing/pytests/endpoint_ready_test.py
  py/kubeflow/kfctl/testing/pytests/kf_is_ready_test.py
  py/kubeflow/kfctl/testing/pytests/kfctl_delete_test.py
  py/kubeflow/kfctl/testing/pytests/kfctl_go_test.py
  py/kubeflow/kfctl/testing/pytests/kfctl_second_apply.py
  py/kubeflow/kfctl/testing/test_deploy.py
  py/kubeflow/kfctl/testing/test_deploy_test.py
  py/kubeflow/kfctl/testing/util/__init__.py
  py/kubeflow/kfctl/testing/util/application_util.py
  py/kubeflow/kfctl/testing/util/application_util_test.py
  py/kubeflow/kfctl/testing/util/deploy_utils.py
  py/kubeflow/kfctl/testing/util/gcp_util.py
  py/kubeflow/kfctl/testing/util/kfctl_go_test_utils.py
  py/kubeflow/kfctl/testing/util/run_with_retry.py
  py/kubeflow/kfctl/testing/util/vm_util.py
Labels: approved, lgtm, size/XXL

#148 Automated cherry pick of #144: fix the bug that only recognize iam sa
  pkg/kfapp/gcp/gcp.go
Labels: approved, lgtm, size/S

#153 Basic auth endpoint fix
  prow_config.yaml
  py/kubeflow/kfctl/testing/util/gcp_util.py
Labels: approved, lgtm, size/M
