Repository kubeflow/kfctl, pull requests merged in 2019-08, with the labels that each got.

#5 Cp from kubeflow
  Dockerfile
  Makefile
  cmd/kfctl/README.md
  cmd/kfctl/cmd/apply.go
  cmd/kfctl/cmd/delete.go
  cmd/kfctl/cmd/generate.go
  cmd/kfctl/cmd/init.go
  cmd/kfctl/cmd/root.go
  cmd/kfctl/cmd/show.go
  cmd/kfctl/main.go
  cmd/plugins/dockerfordesktop/dockerfordesktop.go
  go.mod
  go.sum
  hack/cp_update.sh
  pkg/apis/apps/group.go
  pkg/apis/apps/kfdef/v1alpha1/application_types.go
  pkg/apis/apps/kfdef/v1alpha1/application_types_test.go
  pkg/apis/apps/kfdef/v1alpha1/doc.go
  pkg/apis/apps/kfdef/v1alpha1/register.go
  pkg/apis/apps/kfdef/v1alpha1/zz_generated.deepcopy.go
  pkg/kfapp/aws/aws.go
  pkg/kfapp/aws/aws_plugin.go
  pkg/kfapp/coordinator/coordinator.go
  pkg/kfapp/coordinator/coordinator_test.go
  pkg/kfapp/coordinator/fake/fake.go
  pkg/kfapp/dockerfordesktop/dockerfordesktop.go
  pkg/kfapp/existing_arrikto/existing.go
  pkg/kfapp/gcp/fake/fake.go
  pkg/kfapp/gcp/gcp.go
  pkg/kfapp/gcp/gcp_plugin.go
  pkg/kfapp/gcp/gcp_plugin_test.go
  pkg/kfapp/gcp/gcp_test.go
  pkg/kfapp/gcp/util.go
  pkg/kfapp/kustomize/kustomize.go
  pkg/kfapp/kustomize/kustomize_test.go
  pkg/kfapp/minikube/minikube.go
  pkg/utils/gcputils.go
  pkg/utils/iamutils.go
  pkg/utils/k8utils.go
  prow_config.yaml
  testing/workflows/app.yaml
  testing/workflows/components/kfctl_go_test.jsonnet
  testing/workflows/components/kubeflow_workflow.libsonnet
  testing/workflows/components/params.libsonnet
  testing/workflows/components/util.libsonnet
  testing/workflows/environments/base.libsonnet
  testing/workflows/environments/releasing/main.jsonnet
  testing/workflows/environments/releasing/params.libsonnet
  testing/workflows/lib/v1.7.0/k.libsonnet
  testing/workflows/lib/v1.7.0/k8s.libsonnet
  testing/workflows/lib/v1.7.0/swagger.json
Labels: approved, lgtm, size/XXL

#9 Fix the describe link 'not foud' error.
  pkg/kfapp/coordinator/coordinator.go
Labels: approved, lgtm, ok-to-test, size/XS

#8 sync with kubeflow/bootstrap
  go.mod
  go.sum
  pkg/apis/apps/kfdef/v1alpha1/application_types.go
  pkg/apis/apps/kfdef/v1alpha1/zz_generated.deepcopy.go
  pkg/kfapp/aws/aws.go
  pkg/kfapp/coordinator/coordinator.go
  pkg/kfapp/existing_arrikto/existing.go
  pkg/kfapp/existing_arrikto/existing_test.go
  pkg/kfapp/gcp/gcp.go
  pkg/kfapp/gcp/gcp_test.go
  pkg/kfapp/kustomize/kustomize.go
Labels: approved, lgtm, size/L
