Repository kubeflow/kfctl, pull requests merged in 2020-04, with the labels that each got.

#288 kfctl should support using kustomize to compose a stack of applications
  Makefile
  go.mod
  go.sum
  pkg/kfapp/gcp/gcp.go
  pkg/kfapp/kustomize/kustomize.go
  pkg/kfapp/kustomize/kustomize_test.go
  pkg/kfconfig/types.go
  pkg/kfconfig/types_test.go
Labels: approved, lgtm, size/XL

#297 Revert "Enable istio injection in Kubeflow namespace"
  pkg/utils/k8utils.go
Labels: approved, lgtm, size/S

#300 Support KUBECONFIG environment in building k8s client
  pkg/kfapp/aws/k8sClient.go
Labels: approved, lgtm, size/XS

#302 Automated cherry pick of #300: Support KUBECONFIG environment to v1.0-branch
  pkg/kfapp/aws/k8sClient.go
Labels: approved, lgtm, size/XS

#307 Fix kfctl builds; use gomodules with deepcopy-gen
  Makefile
  cmd/kfctl/cmd/init.go
  go.mod
  go.sum
  hack/boilerplate.go.txt
  py/kubeflow/kfctl/testing/ci/kfctl_e2e_workflow.py
  testing/workflows/components/unit_tests.jsonnet
Labels: approved, lgtm, size/M

#310 Update the build rules for deepcopy gen
  Makefile
  cmd/kfctl/cmd/init.go
Labels: approved, lgtm, size/M

#311 Pin v1.0-branch tests to v1.0.2 manifests
  prow_config.yaml
Labels: approved, lgtm, size/XS

#295 Support patch upgrade
  pkg/kfupgrade/kfupgrade.go
  prow_config.yaml
  py/kubeflow/kfctl/testing/ci/kfctl_upgrade_e2e_workflow.py
Labels: approved, lgtm, size/M

#309 kfctl delete refactor
  cmd/manager/main.go
  go.mod
  go.sum
  pkg/kfapp/kustomize/kustomize.go
  pkg/kfapp/kustomize/kustomize_test.go
  pkg/utils/k8utils.go
  pkg/utils/k8utils_test.go
Labels: approved, lgtm, size/L

#313 Automated cherry pick of #310: Update the build rules for deepcopy gen Cherry pick of #310 on v1.0-branch. #310: Update the build rules for deepcopy gen
  Makefile
Labels: approved, lgtm, size/M

#316 Automated cherry pick of #295: Update config file names Cherry pick of #295 on v1.0-branch. #295: Update config file names
  pkg/kfupgrade/kfupgrade.go
  prow_config.yaml
  py/kubeflow/kfctl/testing/ci/kfctl_upgrade_e2e_workflow.py
Labels: approved, lgtm, size/M

#301 To support stacks kfctl update mapping for spatakus and compute relative directory of cache
  Makefile
  pkg/kfapp/kustomize/kustomize.go
  pkg/kfconfig/types.go
Labels: approved, lgtm, size/S

#319 add myself to approver
  OWNERS
Labels: approved, lgtm, size/XS

#321 Add Dockerfile.ubi and deploy by kustomize for operator
  Makefile
  build/Dockerfile
  build/Dockerfile.ubi
  deploy/cluster_role_binding.yaml
  deploy/crds/kustomization.yaml
  deploy/kustomization.yaml
  deploy/operator.yaml
  deploy/params.yaml
  kustomization.yaml
  kustomize/base/kustomization.yaml
  operator.md
Labels: approved, lgtm, needs-ok-to-test, size/M

#322 Move quota and enable by Kustomize
  deploy/cluster_role_binding.yaml
  deploy/crds/kustomization.yaml
  deploy/kustomization.yaml
  kustomization.yaml
  kustomize/include/quota/kfdef_quota.yaml
  kustomize/include/quota/kustomization.yaml
  operator.md
Labels: approved, lgtm, ok-to-test, size/S

#264 Kustomize cleanup error handling
  Dockerfile
  cmd/kfctl/cmd/apply.go
  cmd/kfctl/cmd/build.go
  cmd/kfctl/cmd/delete.go
  cmd/kfctl/cmd/mirror_build.go
  cmd/kfctl/cmd/mirror_overwrite.go
  cmd/kfctl/cmd/set-image-name.go
  cmd/kfctl/cmd/show.go
  pkg/apis/apps/group.go
  pkg/apis/apps/kfconfig/types.go
  pkg/apis/apps/kfdef/v1alpha1/application_types.go
  pkg/controller/kfdef/kfdef_controller.go
  pkg/kfapp/aws/aws.go
  pkg/kfapp/coordinator/coordinator.go
  pkg/kfapp/gcp/gcp.go
  pkg/kfapp/kustomize/kustomize.go
  pkg/kfconfig/loaders/loaders.go
  pkg/kfconfig/types.go
  pkg/kfupgrade/kfupgrade.go
  pkg/mirror/mirror_image.go
  pkg/mirror/mirror_image_test.go
  pkg/utils/awsutil.go
  pkg/utils/k8utils.go
Labels: approved, lgtm, size/L
