Repository kubeflow/kfctl, pull requests merged in 2020-10, with the labels that each got.

#413 fix: dump generate invalid yaml
  pkg/kfapp/kustomize/kustomize.go
Labels: approved, lgtm, ok-to-test, size/XS

#411 [Operator] various fixes for Kubeflow Operator
  build/Dockerfile.ubi
  operator.md
  pkg/controller/controller.go
  pkg/controller/kfdef/const.go
  pkg/controller/kfdef/kfdef_controller.go
  pkg/kfapp/kustomize/kustomize.go
  pkg/kfapp/kustomize/kustomize_test.go
  pkg/kfapp/kustomize/testdata/operator/expected/service.yaml
  pkg/utils/k8utils.go
Labels: approved, lgtm, size/L

#416 hardcoded 'kubeflow' deployment name
  operator.md
Labels: approved, lgtm, size/XS

#417 Update Troubleshooting on the Known issues for Kubeflow 1.1
  operator.md
Labels: approved, lgtm, size/XS

#419 [IBM] limit reconcile requests to specific kfdef update events and a couple of operator fixes
  deploy/operator.yaml
  pkg/controller/kfdef/kfdef_controller.go
  pkg/kfapp/kustomize/kustomize.go
Labels: approved, lgtm, size/M

#423 Add PatrickXYS as approver
  OWNERS
Labels: approved, lgtm, size/XS

#426 Remove GCP kfctl E2E tests on the 1.0 branch
  prow_config.yaml
Labels: approved, lgtm, size/M

#425 Remove all kfctl GCP e2e tests on the 1.1 branch.
  prow_config.yaml
Labels: approved, lgtm, size/M
