Repository kubeflow/kfctl, pull requests merged in 2020-01, with the labels that each got.

#160 Automated cherry pick of #80: Add missing files Cherry pick of #80 on v0.7-branch. #80: Add missing files
  config/zz_generated.deepcopy.go
  pkg/kfupgrade/kfupgrade.go.back
Labels: approved, lgtm, size/L

#162 Fix Makefile for Darwin
  Makefile
Labels: approved, lgtm, size/XS

#163 Automated cherry pick of #162: Fix Makefile for Darwin Cherry pick of #162 on v0.7-branch. #162: Fix Makefile for Darwin
  Makefile
Labels: approved, lgtm, size/XS

#164 Fix makefile issue
  Makefile
  go.mod
Labels: approved, lgtm, size/XS

#165 update profile test dir in e2e test
  py/kubeflow/kfctl/testing/ci/kfctl_e2e_workflow.py
Labels: approved, lgtm, size/S

#169 fix kfctl
  go.mod
  go.sum
  pkg/kfconfig/types.go
Labels: approved, lgtm, size/L

#171 cherry pick https://github.com/kubeflow/kfctl/pull/169 to v0.7 branch
  go.mod
  go.sum
  pkg/apis/apps/kfconfig/types.go
  py/kubeflow/kfctl/testing/ci/kfctl_e2e_workflow.py
Labels: approved, lgtm, size/L

#173 remove platform from kustomize.go
  pkg/kfapp/kustomize/kustomize.go
  pkg/kfconfig/types.go
Labels: approved, lgtm, size/XS

#176 fix SetTokenSource
  pkg/kfapp/gcp/gcp.go
Labels: approved, lgtm, size/XS

#179 filter secrets during "kfconfig -> kfdef" instead of "kfdef -> kfconfig"
  pkg/kfconfig/loaders/v1.go
  pkg/kfconfig/loaders/v1beta1.go
Labels: approved, lgtm, size/S

#180 kfconfig loader for kfdef v1 should import kfdef v1
  pkg/kfconfig/loaders/v1.go
Labels: approved, lgtm, size/XS

#183 Update dependency to remove bou.ke/monkey
  go.mod
  go.sum
Labels: approved, lgtm, size/L

#172 Kfctl upgrade e2e test
  pkg/kfupgrade/kfupgrade.go
  prow_config.yaml
  py/kubeflow/kfctl/testing/ci/kfctl_e2e_workflow.py
  py/kubeflow/kfctl/testing/ci/kfctl_upgrade_e2e_workflow.py
  py/kubeflow/kfctl/testing/pytests/conftest.py
  py/kubeflow/kfctl/testing/pytests/kfctl_upgrade_test.py
  py/kubeflow/kfctl/testing/util/kfctl_go_test_utils.py
Labels: approved, lgtm, size/L

#168 Add kfctl third party licenses
  Dockerfile
  Makefile
  third_party/README.md
  third_party/check-license.sh
  third_party/concatenate_license.py
  third_party/dep.txt
  third_party/dep_repo.manual.csv
  third_party/license.txt
  third_party/license_info.csv
Labels: approved, lgtm, size/XXL

#166 kfam e2e test
  py/kubeflow/kfctl/testing/ci/kfctl_e2e_workflow.py
  py/kubeflow/kfctl/testing/pytests/kfam_test.py
Labels: approved, lgtm, size/M

#181 Adding myself in Owners file
  OWNERS
Labels: approved, lgtm, size/XS

#188 Fix build-kfctl to copy the correct binary on darwin arch
  Makefile
Labels: approved, lgtm, ok-to-test, size/XS

#190 add retry to kfam e2e test
  py/kubeflow/kfctl/testing/pytests/kfam_test.py
Labels: approved, lgtm, size/S

#196 Update kfupgrade prow to include more specific dirs
  prow_config.yaml
Labels: approved, lgtm, size/XS

#187 Fix kustomize secretGenerator merging bug
  pkg/kfapp/kustomize/kustomize.go
Labels: approved, lgtm, size/M

#189 Initial operator code
  .gitignore
  build/Dockerfile
  build/bin/entrypoint
  build/bin/user_setup
  cmd/manager/main.go
  deploy/cluster_role_binding.yaml
  deploy/crds/kfdef.apps.kubeflow.org_kfdefs_crd.yaml
  deploy/crds/kfdef_quota.yaml
  deploy/operator.yaml
  deploy/service_account.yaml
  go.mod
  go.sum
  operator.md
  pkg/apis/apps/addtoscheme_kfdef_v1.go
  pkg/apis/apps/apis.go
  pkg/apis/apps/group.go
  pkg/controller/controller.go
  pkg/controller/kfdef/const.go
  pkg/controller/kfdef/kfdef_controller.go
  pkg/kfconfig/loaders/loaders_test.go
Labels: approved, lgtm, size/XXL

#202 Update docs
  README.md
  operator.md
Labels: approved, lgtm, size/XS

#203 Add a pointer for kfdef usage, and fix dome docs issues
  README.md
  operator.md
Labels: approved, lgtm, size/XS

#200 Mark the pytorch job test as flaky; kubeflow/kfctl#199
  py/kubeflow/kfctl/testing/pytests/pytorch_job_deploy.py
Labels: approved, lgtm, size/XS

#198 Fix katib deployment tests
  py/kubeflow/kfctl/testing/pytests/kf_is_ready_test.py
  py/kubeflow/kfctl/testing/test_deploy.py
Labels: approved, lgtm, size/XS

#201 Make kfctl show and set-image-name alpha commands
  cmd/kfctl/cmd/alpha.go
  cmd/kfctl/cmd/set-image-name.go
  cmd/kfctl/cmd/show.go
Labels: approved, lgtm, size/S
