Repository kubeflow/kfctl, pull requests merged in 2020-02, with the labels that each got.

#211 Increase the timeout for kustomize apply to give certmanager more time kubeflow/manifests#806
  pkg/kfapp/kustomize/kustomize.go
Labels: approved, lgtm, size/S

#212 fixing name of secretGenerator key in kustomize file generation
  pkg/kfapp/kustomize/testdata/kustomizeExample/pytorch-operator/expected/kustomization.yaml
  pkg/kfapp/kustomize/testdata/kustomizeExample/pytorch-operator/overlays/application/kustomization.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#207 Update kfctl test to v0.7.1 -> v1.0.0
  pkg/kfupgrade/kfupgrade.go
  prow_config.yaml
  py/kubeflow/kfctl/testing/pytests/kfam_test.py
Labels: approved, lgtm, size/S

#216 Update katib deployment tests
  py/kubeflow/kfctl/testing/pytests/kf_is_ready_test.py
  py/kubeflow/kfctl/testing/test_deploy.py
Labels: approved, lgtm, size/S

#218 Fix kfctl_second_apply test
  pkg/kfapp/gcp/gcp.go
  py/kubeflow/kfctl/testing/pytests/kfctl_second_apply.py
Labels: approved, lgtm, size/XS

#219 Automated cherry pick of #218: test Cherry pick of #218 on v1.0-branch. #218: test
  pkg/kfapp/gcp/gcp.go
  py/kubeflow/kfctl/testing/pytests/kfctl_second_apply.py
Labels: approved, lgtm, size/XS

#220 bump kustomize dependency to v3.2.0
  go.mod
  go.sum
Labels: approved, lgtm, size/S

#208 initial code for registering operator to olm
  deploy/olm-catalog/kfctl/0.1.0/kfctl.v0.1.0.apps.kubeflow.org_kfdefs_crd.yaml
  deploy/olm-catalog/kfctl/0.1.0/kfctl.v0.1.0.clusterserviceversion.yaml
  deploy/olm-catalog/kfctl/kfctl.package.yaml
  deploy/role.yaml
  operator.md
Labels: approved, lgtm, size/L

#224 Update operator csv with more info
  deploy/olm-catalog/kfctl/0.1.0/kfctl.v0.1.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#223 Add tests to check status metadata deployments
  py/kubeflow/kfctl/testing/pytests/kf_is_ready_test.py
Labels: approved, lgtm, size/M

#234 Update config file names to 1.0
  cmd/kfctl/cmd/apply.go
  cmd/kfctl/cmd/build.go
  pkg/kfapp/kustomize/kustomize.go
Labels: approved, lgtm, size/S

#186 fails kfctl if overlays not found
  pkg/kfapp/kustomize/kustomize.go
Labels: approved, lgtm, ok-to-test, size/XS

#230 Update jupyter_test using v1 spec
  py/kubeflow/kfctl/testing/pytests/jupyter_test.py
  py/kubeflow/kfctl/testing/pytests/testdata/jupyter_test.yaml
Labels: approved, lgtm, size/XS

#238 Automated cherry pick of #234: Update config file names Cherry pick of #234 on v1.0-branch. #234: Update config file names
  cmd/kfctl/cmd/apply.go
  cmd/kfctl/cmd/build.go
  pkg/kfapp/kustomize/kustomize.go
Labels: approved, lgtm, size/S

#225 Add IAM Role and Policy for Service Account support
  go.mod
  go.sum
  pkg/kfapp/aws/aws.go
  pkg/kfapp/aws/identity.go
  pkg/kfconfig/awsplugin/types.go
  pkg/kfconfig/awsplugin/zz_generated.deepcopy.go
  pkg/utils/awsutil.go
Labels: approved, lgtm, size/XL

#239 mirror overwrite: drop image tags before write back
  pkg/mirror/mirror_image.go
  pkg/mirror/testdata/expected-kustomization.yaml
Labels: approved, lgtm, size/S

#244 update operator build instruction using makefile
  Makefile
  operator.md
Labels: approved, lgtm, size/M

#245 use py3 img only in endpoint_is_ready
  py/kubeflow/kfctl/testing/ci/kfctl_e2e_workflow.py
Labels: approved, lgtm, size/XS

#248 Update operator instructions for using the default kubeflow kfdef
  operator.md
Labels: approved, lgtm, size/S

#251 Fix license issue: update go.mod to remove bou.ke/monkey dependency
  go.mod
  go.sum
Labels: approved, lgtm, ok-to-test, size/XS
