Repository kubeflow/kfctl, pull requests merged in 2020-03, with the labels that each got.

#258 Replace logger in operator controller code to make it consistent with other kfctl code
  go.mod
  pkg/controller/kfdef/kfdef_controller.go
Labels: approved, lgtm, ok-to-test, size/M

#254 Improve kfctl for AWS
  go.mod
  go.sum
  pkg/kfapp/aws/OWNERS
  pkg/kfapp/aws/aws.go
  pkg/kfapp/aws/eks.go
  pkg/kfapp/aws/eks_test.go
  pkg/kfapp/aws/identity.go
  pkg/kfapp/aws/k8sClient.go
  pkg/kfconfig/awsplugin/OWNERS
  pkg/kfconfig/awsplugin/types.go
  pkg/kfconfig/awsplugin/zz_generated.deepcopy.go
  pkg/kfconfig/types.go
  pkg/kfconfig/types_test.go
  pkg/utils/awsutil.go
Labels: approved, lgtm, size/XXL

#267 Create OIDC secret and pass to alb-ingress-controller
  pkg/kfapp/aws/aws.go
  pkg/kfapp/aws/k8sClient.go
Labels: approved, lgtm, size/M

#259 fix typo to avoid panic in operator controller
  pkg/controller/kfdef/kfdef_controller.go
Labels: approved, lgtm, ok-to-test, size/XS

#268 Cherry-pick #225 #254 #267 to v1.0-branch
  go.mod
  go.sum
  pkg/kfapp/aws/OWNERS
  pkg/kfapp/aws/aws.go
  pkg/kfapp/aws/eks.go
  pkg/kfapp/aws/eks_test.go
  pkg/kfapp/aws/identity.go
  pkg/kfapp/aws/k8sClient.go
  pkg/kfconfig/awsplugin/OWNERS
  pkg/kfconfig/awsplugin/types.go
  pkg/kfconfig/awsplugin/zz_generated.deepcopy.go
  pkg/kfconfig/types.go
  pkg/kfconfig/types_test.go
  pkg/utils/awsutil.go
Labels: approved, lgtm, size/XXL

#261 reviewers for operator related issues and PRS
  OWNERS
Labels: approved, lgtm, size/XS

#270 update operator name from kfctl to kubeflow in OLM
  deploy/olm-catalog/kfctl/kfctl.package.yaml
  deploy/olm-catalog/kubeflow/0.1.0/kfdef.apps.kubeflow.org.crd.yaml
  deploy/olm-catalog/kubeflow/0.1.0/kubeflow.v0.1.0.clusterserviceversion.yaml
  deploy/olm-catalog/kubeflow/kubeflow.package.yaml
Labels: approved, lgtm, size/S

#275 streamline operator install steps
  operator.md
Labels: approved, lgtm, size/S

#273 Create Istio-system namespace before create OIDC secret
  pkg/kfapp/aws/aws.go
Labels: approved, lgtm, ok-to-test, size/XS

#276 Automated cherry pick of #273: Create Istio-system namespace before create OIDC secret Cherry pick of #273 on v1.0-branch. #273: Create Istio-system namespace before create OIDC secret
  pkg/kfapp/aws/aws.go
Labels: approved, lgtm, ok-to-test, size/XS

#271 add ownerReference to resources when deployed through operator
  operator.md
  pkg/controller/kfdef/kfdef_controller.go
  pkg/kfapp/kustomize/kustomize.go
  pkg/utils/k8utils.go
Labels: approved, lgtm, size/L

#282 Find User Default Region and Cred Setting
  pkg/kfapp/aws/aws.go
Labels: approved, lgtm, needs-ok-to-test, size/XS

#286 Automated cherry pick of #282: Find User Default Region and Cred Setting Cherry pick of #282 on v1.0-branch. #282: Find User Default Region and Cred Setting
  pkg/kfapp/aws/aws.go
Labels: approved, lgtm, needs-ok-to-test, size/XS

#131 Enable istio injection in Kubeflow namespace
  pkg/utils/k8utils.go
Labels: approved, lgtm, size/S

#272 Return error when the cache path is a sub directory of local manifests repo
  pkg/kfconfig/types.go
  pkg/kfconfig/types_test.go
Labels: approved, lgtm, size/M

#292 add unit test
  pkg/kfapp/kustomize/kustomize_test.go
  pkg/kfapp/kustomize/testdata/doc.go
  pkg/kfapp/kustomize/testdata/operator/base/kustomization.yaml
  pkg/kfapp/kustomize/testdata/operator/base/service.yaml
  pkg/kfapp/kustomize/testdata/operator/expected/service.yaml
  pkg/kfapp/kustomize/testdata/operator/kustomization.yaml
Labels: approved, lgtm, size/M

#221 bump kustomize dependency to v3.2.0 (#220)
  go.mod
  go.sum
Labels: approved, lgtm, size/S

#291 GCP: remove dependecies from DM & IAM hack
  pkg/kfapp/gcp/gcp.go
  pkg/kfapp/gcp/gcp_test.go
  pkg/kfconfig/types_test.go
Labels: approved, lgtm, size/L
