Repository kubeflow/kfctl, pull requests merged in 2020-05, with the labels that each got.

#325 Fixes syntax error in Dockerfile
  Dockerfile
Labels: approved, lgtm, needs-ok-to-test, size/XS

#323 Fix typo: fucntionalities -> functionalities
  README.md
Labels: size/XS

#324 tie kfapp directory with kfdef name and namespace
  go.mod
  pkg/controller/kfdef/const.go
  pkg/controller/kfdef/kfdef_controller.go
Labels: approved, lgtm, size/M

#337 Update README.md
  README.md
Labels: approved, lgtm, ok-to-test, size/XS

#334 update operator doc and add me back to reviewer
  OWNERS
  operator.md
Labels: approved, lgtm, size/L

#329 Add --dump flag to build
  cmd/kfctl/cmd/build.go
  go.mod
  pkg/apis/apps/group.go
  pkg/kfapp/aws/aws.go
  pkg/kfapp/coordinator/coordinator.go
  pkg/kfapp/coordinator/fake/fake.go
  pkg/kfapp/dockerfordesktop/dockerfordesktop.go
  pkg/kfapp/existing_arrikto/existing.go
  pkg/kfapp/gcp/fake/fake.go
  pkg/kfapp/gcp/gcp.go
  pkg/kfapp/kustomize/kustomize.go
  pkg/kfapp/minikube/minikube.go
  pkg/kfupgrade/kfupgrade.go
Labels: approved, lgtm, size/L
