Repository kubeflow/kfctl, pull requests merged in 2020-06, with the labels that each got.

#318 Enable arm64 kfctl binary build and fix docker build error
  Dockerfile
  Makefile
Labels: approved, lgtm, size/M

#348 Revert "Enable arm64 kfctl binary build and fix docker build error"
  Dockerfile
  Makefile
Labels: approved, lgtm, size/M

#349 Update: Enable arm64 kfctl binary build and fix docker build error
  Dockerfile
  Makefile
Labels: approved, lgtm, size/M

#351 Add the ability to create CloudEndpoint resources using kfctl.
  cmd/kfctl/cmd/apply.go
  cmd/kfctl/cmd/build.go
  go.mod
  go.sum
Labels: approved, lgtm, size/L

#346 Do not run KF E2E tests as blocking presubmits.
  prow_config.yaml
Labels: approved, lgtm, size/M

#342 kfctl mirror should recourse over dependencies
  cmd/kfctl/cmd/mirror_build.go
  cmd/kfctl/cmd/root.go
  go.mod
  go.sum
  pkg/mirror/mirror_image.go
  pkg/mirror/mirror_image_test.go
  pkg/mirror/testdata/base-pkg/kustomization.yaml
  pkg/mirror/testdata/expected-cloudbuild.yaml
  pkg/mirror/testdata/expected-kustomization.yaml
  pkg/mirror/testdata/expected-pipeline.yaml
  pkg/mirror/testdata/kustomize/kustomization.yaml
  pkg/utils/diff.go
Labels: approved, lgtm, size/L

#350 fix error when config file is from local relative directory
  pkg/kfconfig/types.go
  pkg/kfconfig/types_test.go
Labels: approved, lgtm, size/M

#354 Update endpoint_ready_test for blueprints
  py/kubeflow/__init__.py
  py/kubeflow/kfctl/testing/pytests/endpoint_ready_test.py
  py/kubeflow/kfctl/testing/util/gcp_util.py
Labels: approved, lgtm, size/L

#355 Update kf_is_ready_test.py to work with GCP blueprints
  py/kubeflow/kfctl/testing/pytests/kf_is_ready_test.py
Labels: approved, lgtm, size/S

#356 handle generator with envs
  pkg/kfapp/kustomize/kustomize.go
  pkg/kfapp/kustomize/kustomize_test.go
  pkg/kfapp/kustomize/testdata/kustomizeExample/metadata/base/grpc-params.env
  pkg/kfapp/kustomize/testdata/kustomizeExample/metadata/base/kustomization.yaml
  pkg/kfapp/kustomize/testdata/kustomizeExample/metadata/base/metadata-deployment.yaml
  pkg/kfapp/kustomize/testdata/kustomizeExample/metadata/base/metadata-envoy-deployment.yaml
  pkg/kfapp/kustomize/testdata/kustomizeExample/metadata/base/metadata-envoy-service.yaml
  pkg/kfapp/kustomize/testdata/kustomizeExample/metadata/base/metadata-service.yaml
  pkg/kfapp/kustomize/testdata/kustomizeExample/metadata/base/metadata-ui-deployment.yaml
  pkg/kfapp/kustomize/testdata/kustomizeExample/metadata/base/metadata-ui-role.yaml
  pkg/kfapp/kustomize/testdata/kustomizeExample/metadata/base/metadata-ui-rolebinding.yaml
  pkg/kfapp/kustomize/testdata/kustomizeExample/metadata/base/metadata-ui-sa.yaml
  pkg/kfapp/kustomize/testdata/kustomizeExample/metadata/base/metadata-ui-service.yaml
  pkg/kfapp/kustomize/testdata/kustomizeExample/metadata/base/params.env
  pkg/kfapp/kustomize/testdata/kustomizeExample/metadata/expected/kustomization.yaml
  pkg/kfapp/kustomize/testdata/kustomizeExample/metadata/overlays/application/application.yaml
  pkg/kfapp/kustomize/testdata/kustomizeExample/metadata/overlays/application/kustomization.yaml
  pkg/kfapp/kustomize/testdata/kustomizeExample/metadata/overlays/db/kustomization.yaml
  pkg/kfapp/kustomize/testdata/kustomizeExample/metadata/overlays/db/metadata-db-deployment.yaml
  pkg/kfapp/kustomize/testdata/kustomizeExample/metadata/overlays/db/metadata-db-pvc.yaml
  pkg/kfapp/kustomize/testdata/kustomizeExample/metadata/overlays/db/metadata-db-service.yaml
  pkg/kfapp/kustomize/testdata/kustomizeExample/metadata/overlays/db/metadata-deployment.yaml
  pkg/kfapp/kustomize/testdata/kustomizeExample/metadata/overlays/db/params.env
  pkg/kfapp/kustomize/testdata/kustomizeExample/metadata/overlays/db/secrets.env
  pkg/kfapp/kustomize/testdata/kustomizeExample/metadata/overlays/external-mysql/kustomization.yaml
  pkg/kfapp/kustomize/testdata/kustomizeExample/metadata/overlays/external-mysql/metadata-deployment.yaml
  pkg/kfapp/kustomize/testdata/kustomizeExample/metadata/overlays/external-mysql/params.env
  pkg/kfapp/kustomize/testdata/kustomizeExample/metadata/overlays/external-mysql/secrets.env
  pkg/kfapp/kustomize/testdata/kustomizeExample/metadata/overlays/google-cloudsql/README.md
  pkg/kfapp/kustomize/testdata/kustomizeExample/metadata/overlays/google-cloudsql/kustomization.yaml
  pkg/kfapp/kustomize/testdata/kustomizeExample/metadata/overlays/google-cloudsql/metadata-deployment.yaml
  pkg/kfapp/kustomize/testdata/kustomizeExample/metadata/overlays/google-cloudsql/params.env
  pkg/kfapp/kustomize/testdata/kustomizeExample/metadata/overlays/ibm-storage-config/kustomization.yaml
  pkg/kfapp/kustomize/testdata/kustomizeExample/metadata/overlays/istio/kustomization.yaml
  pkg/kfapp/kustomize/testdata/kustomizeExample/metadata/overlays/istio/params.yaml
  pkg/kfapp/kustomize/testdata/kustomizeExample/metadata/overlays/istio/virtual-service-metadata-grpc.yaml
  pkg/kfapp/kustomize/testdata/kustomizeExample/metadata/overlays/istio/virtual-service.yaml
Labels: approved, lgtm, size/XL

#338 Update OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#359 Add aws region into IRSA role name
  pkg/kfapp/aws/aws.go
Labels: approved, lgtm, size/S

#357 Add Support for AWS Dex Basic-Authentication
  pkg/kfapp/aws/aws.go
  pkg/kfconfig/awsplugin/types.go
  pkg/kfconfig/awsplugin/zz_generated.deepcopy.go
Labels: approved, lgtm, size/M

#361 Automated cherry pick of #356: handle generator with envs Cherry pick of #356 on v1.1-branch. #356: handle generator with envs
  pkg/kfapp/kustomize/kustomize.go
  pkg/kfapp/kustomize/kustomize_test.go
  pkg/kfapp/kustomize/testdata/kustomizeExample/metadata/base/grpc-params.env
  pkg/kfapp/kustomize/testdata/kustomizeExample/metadata/base/kustomization.yaml
  pkg/kfapp/kustomize/testdata/kustomizeExample/metadata/base/metadata-deployment.yaml
  pkg/kfapp/kustomize/testdata/kustomizeExample/metadata/base/metadata-envoy-deployment.yaml
  pkg/kfapp/kustomize/testdata/kustomizeExample/metadata/base/metadata-envoy-service.yaml
  pkg/kfapp/kustomize/testdata/kustomizeExample/metadata/base/metadata-service.yaml
  pkg/kfapp/kustomize/testdata/kustomizeExample/metadata/base/metadata-ui-deployment.yaml
  pkg/kfapp/kustomize/testdata/kustomizeExample/metadata/base/metadata-ui-role.yaml
  pkg/kfapp/kustomize/testdata/kustomizeExample/metadata/base/metadata-ui-rolebinding.yaml
  pkg/kfapp/kustomize/testdata/kustomizeExample/metadata/base/metadata-ui-sa.yaml
  pkg/kfapp/kustomize/testdata/kustomizeExample/metadata/base/metadata-ui-service.yaml
  pkg/kfapp/kustomize/testdata/kustomizeExample/metadata/base/params.env
  pkg/kfapp/kustomize/testdata/kustomizeExample/metadata/expected/kustomization.yaml
  pkg/kfapp/kustomize/testdata/kustomizeExample/metadata/overlays/application/application.yaml
  pkg/kfapp/kustomize/testdata/kustomizeExample/metadata/overlays/application/kustomization.yaml
  pkg/kfapp/kustomize/testdata/kustomizeExample/metadata/overlays/db/kustomization.yaml
  pkg/kfapp/kustomize/testdata/kustomizeExample/metadata/overlays/db/metadata-db-deployment.yaml
  pkg/kfapp/kustomize/testdata/kustomizeExample/metadata/overlays/db/metadata-db-pvc.yaml
  pkg/kfapp/kustomize/testdata/kustomizeExample/metadata/overlays/db/metadata-db-service.yaml
  pkg/kfapp/kustomize/testdata/kustomizeExample/metadata/overlays/db/metadata-deployment.yaml
  pkg/kfapp/kustomize/testdata/kustomizeExample/metadata/overlays/db/params.env
  pkg/kfapp/kustomize/testdata/kustomizeExample/metadata/overlays/db/secrets.env
  pkg/kfapp/kustomize/testdata/kustomizeExample/metadata/overlays/external-mysql/kustomization.yaml
  pkg/kfapp/kustomize/testdata/kustomizeExample/metadata/overlays/external-mysql/metadata-deployment.yaml
  pkg/kfapp/kustomize/testdata/kustomizeExample/metadata/overlays/external-mysql/params.env
  pkg/kfapp/kustomize/testdata/kustomizeExample/metadata/overlays/external-mysql/secrets.env
  pkg/kfapp/kustomize/testdata/kustomizeExample/metadata/overlays/google-cloudsql/README.md
  pkg/kfapp/kustomize/testdata/kustomizeExample/metadata/overlays/google-cloudsql/kustomization.yaml
  pkg/kfapp/kustomize/testdata/kustomizeExample/metadata/overlays/google-cloudsql/metadata-deployment.yaml
  pkg/kfapp/kustomize/testdata/kustomizeExample/metadata/overlays/google-cloudsql/params.env
  pkg/kfapp/kustomize/testdata/kustomizeExample/metadata/overlays/ibm-storage-config/kustomization.yaml
  pkg/kfapp/kustomize/testdata/kustomizeExample/metadata/overlays/istio/kustomization.yaml
  pkg/kfapp/kustomize/testdata/kustomizeExample/metadata/overlays/istio/params.yaml
  pkg/kfapp/kustomize/testdata/kustomizeExample/metadata/overlays/istio/virtual-service-metadata-grpc.yaml
  pkg/kfapp/kustomize/testdata/kustomizeExample/metadata/overlays/istio/virtual-service.yaml
Labels: approved, lgtm, size/XL

#362 Pretty print log messages IAM policy(from #327)
  pkg/kfapp/aws/aws.go
  pkg/utils/iamutils.go
Labels: approved, lgtm, size/XS

#363 Cherry pick #357 #359 #362 to v1.1-branch
  pkg/kfapp/aws/aws.go
  pkg/kfconfig/awsplugin/types.go
  pkg/kfconfig/awsplugin/zz_generated.deepcopy.go
  pkg/utils/iamutils.go
Labels: approved, lgtm, size/L

#367 Cherry pick #338 to v1.1-branch
  OWNERS
Labels: approved, lgtm, size/XS
