Repository kubeflow/kfctl, pull requests merged in 2020-08, with the labels that each got.

#388 Turn the remove-namespace kustomize function into a proper function.
  kustomize-fns/Makefile
  kustomize-fns/main.go
  kustomize-fns/remove-namespace/function.go
  kustomize-fns/remove-namespace/function_test.go
  kustomize-fns/remove-namespace/go.mod
  kustomize-fns/remove-namespace/go.sum
  kustomize-fns/remove-namespace/main.go
  kustomize-fns/remove-namespace/skaffold.yaml
  kustomize-fns/remove-namespace/test_data/in_cluster_resource.yaml
  kustomize-fns/remove-namespace/test_data/ns_resource.yaml
  kustomize-fns/remove-namespace/test_data/out_cluster_resource.yaml
Labels: approved, lgtm, size/XL

#390 Create a kustomize function to set the gateway on virtual services.
  kustomize-fns/image-prefix/function.go
  kustomize-fns/latest_image.json
  kustomize-fns/main.go
  kustomize-fns/remove-namespace/function.go
  kustomize-fns/virtual-service/function.go
  kustomize-fns/virtual-service/function_test.go
  kustomize-fns/virtual-service/test_data/expected.yaml
  kustomize-fns/virtual-service/test_data/input.yaml
Labels: approved, lgtm, size/L

#394 Remove jlewi@ from the root OWNERs file.
  OWNERS
Labels: approved, lgtm, size/XS

#387 Add Jeffwan as approver
  OWNERS
Labels: approved, lgtm, size/XS

#397 Fix build error for int to string conversion (#396)
  pkg/kfapp/aws/aws.go
Labels: approved, lgtm, ok-to-test, size/XS

#386 Add intelligent kustomize sorting in apply and delete
  pkg/kfapp/kustomize/kustomize.go
  pkg/utils/kindsorter.go
Labels: approved, lgtm, size/L
