Repository kubeflow/kfctl, pull requests merged in 2020-07, with the labels that each got.

#368 Fix the IAP endpoint_ready_test
  py/kubeflow/kfctl/testing/util/gcp_util.py
Labels: approved, lgtm, size/S

#365 update operator image version for release 1.1
  cmd/manager/main.go
  deploy/operator.yaml
Labels: approved, lgtm, size/XS

#369 test(pipelines): update deployment list for test_pipeline_is_ready
  py/kubeflow/kfctl/testing/pytests/kf_is_ready_test.py
Labels: approved, lgtm, size/XS

#370 test: test_pipeline_is_ready - fix cache-deployer deployment name
  py/kubeflow/kfctl/testing/pytests/kf_is_ready_test.py
Labels: approved, lgtm, size/XS

#372 Fix kf_is_ready_test
  py/kubeflow/kfctl/testing/pytests/kf_is_ready_test.py
Labels: approved, lgtm, size/L

#374 Add an explicit platform parameter to the kf_is_ready_test.py
  py/kubeflow/kfctl/testing/pytests/conftest.py
  py/kubeflow/kfctl/testing/pytests/kf_is_ready_test.py
Labels: approved, lgtm, size/S

#375 Fix tests for GCP blueprints 1.1
  py/kubeflow/kfctl/testing/pytests/kf_is_ready_test.py
Labels: approved, lgtm, size/M

#378 Adapt to v3 manifest for aws
  pkg/kfapp/aws/aws.go
  pkg/kfconfig/types.go
  pkg/utils/awsutil.go
Labels: approved, lgtm, size/XS

#379 Improve AWS kfctl
  pkg/kfapp/aws/aws.go
Labels: approved, lgtm, size/XS

#380 Use istio-parameter in manifests
  pkg/kfapp/aws/aws.go
  pkg/kfconfig/types.go
Labels: approved, lgtm, size/XS

#381 Cherry pick #378 #379 #380 to v1.1-branch
  pkg/kfapp/aws/aws.go
  pkg/kfconfig/types.go
  pkg/utils/awsutil.go
Labels: approved, lgtm, size/S

#382 Add PatrickXYS into reviewer
  OWNERS
Labels: approved, lgtm, size/XS

#377 Check KFServing installation
  py/kubeflow/kfctl/testing/ci/kfctl_e2e_workflow.py
  py/kubeflow/kfctl/testing/pytests/kf_is_ready_test.py
Labels: approved, lgtm, size/XL
