Repository kubeflow/kfctl, pull requests merged in 2020-11, with the labels that each got.

#326 Fix syncing cache behind HTTP proxy
  pkg/kfconfig/types.go
Labels: approved, lgtm, ok-to-test, size/XS

#432 Test against k8s python-client version 12.0
  py/kubeflow/kfctl/testing/ci/kfctl_e2e_workflow.py
Labels: approved, lgtm, size/XS

#439 Remove autoscaler-hpa knative deployment check
  py/kubeflow/kfctl/testing/pytests/kf_is_ready_test.py
Labels: approved, lgtm, size/XS

#440 test: remove metadata UI/server readiness test
  py/kubeflow/kfctl/testing/pytests/kf_is_ready_test.py
Labels: approved, lgtm, size/XS

#434 Add daemonset status check support
  py/kubeflow/kfctl/testing/pytests/kf_is_ready_test.py
Labels: approved, lgtm, size/S

#441 Cherry-pick of #439 and #440 to v1.2-branch
  py/kubeflow/kfctl/testing/pytests/kf_is_ready_test.py
Labels: approved, lgtm, size/XS

#438 fail build on missing application name
  pkg/kfconfig/loaders/v1.go
  pkg/kfconfig/types.go
Labels: approved, lgtm, ok-to-test, size/S

#445 Automated cherry pick of #434: Add Daemonset status check support
  py/kubeflow/kfctl/testing/pytests/kf_is_ready_test.py
Labels: approved, lgtm, size/S

#446 Automated cherry pick of #438: fail build on missing application name
  pkg/kfconfig/loaders/v1.go
  pkg/kfconfig/types.go
Labels: approved, lgtm, size/S

#444 Add configuration for eks_cluster_version
  py/kubeflow/kfctl/testing/ci/kfctl_e2e_workflow.py
  py/kubeflow/kfctl/testing/pytests/conftest.py
  py/kubeflow/kfctl/testing/pytests/kfctl_create_cluster_test.py
Labels: approved, lgtm, size/S

#448 Fix csv version
  deploy/olm-catalog/kubeflow/1.1.0/kubeflow.v1.1.0.clusterserviceversion.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#449 Update version output to 1.2.0
  cmd/manager/main.go
Labels: approved, lgtm, ok-to-test, size/XS

#451 Fixed the default output to point to `1.2` instead of `1.0`
  cmd/kfctl/cmd/apply.go
Labels: approved, lgtm, needs-ok-to-test, size/XS

#453 Fixed the default output to point to `1.2` instead of `1.0`
  cmd/kfctl/cmd/apply.go
Labels: approved, lgtm, needs-ok-to-test, size/XS

#452 Update version output to 1.2.0 (#449)
  cmd/manager/main.go
Labels: approved, lgtm, ok-to-test, size/XS

#263 fix: change occasional usage of kebab case to snake case
  pkg/apis/apps/group.go
Labels: approved, lgtm, size/XS

#456 Improve README.md
  README.md
Labels: approved, lgtm, size/XS
